BD/project/project/urls.py
from django.contrib import admin
from django.urls import path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('main/', views.main, name='main'),
    path('create_shop/', views.create_shop, name='create_shop'),
    path('list_view/', views.list_view, name='list_view'),
    path('shop/<id>/', views.detail_shop, name='detail_shop'),
    path('staff/<id>/', views.detail_staff, name='detail_staff'),
    path('rank/<id>/', views.detail_rank, name='detail_rank'),
    path('payment/<id>/', views.detail_payment, name='detail_payment'),
    path('attendance/<id>/', views.detail_attendance, name='detail_attendance'),
    path('income/<id>/', views.detail_income, name='detail_income'),
    path('genre/<id>/', views.detail_genre, name='detail_genre'),
    path('film/<id>/', views.detail_film, name='detail_film'),
    path('equipment/<id>/', views.detail_equipment, name='detail_equipment'),
    path('film_review/<id>/', views.detail_film_review, name='detail_film_review'),
    path('shop/<id>/update', views.update_shop, name='update_shop'),
    path('staff/<id>/update', views.update_staff, name='update_staff'),
    path('rank/<id>/update', views.update_rank, name='update_rank'),
    path('payment/<id>/update', views.update_payment, name='update_payment'),
    path('attendance/<id>/update', views.update_attendance,
         name='update_attendance'),
    path('income/<id>/update', views.update_income, name='update_income'),
    path('genre/<id>/update', views.update_genre, name='update_genre'),
    path('film/<id>/update', views.update_film, name='update_film'),
    path('equipment/<id>/update', views.update_equipment, name='update_equipment'),
    path('film_review/<id>/update', views.update_film_review,
         name='update_film_review'),
    path('<id>/delete', views.delete_view, name='delete_view'),
    path('shop/<id>/delete', views.delete_shop, name='delete_shop'),
    path('staff/<id>/delete', views.delete_staff, name='delete_staff'),
    path('rank/<id>/delete', views.delete_rank, name='delete_rank'),
    path('payment/<id>/delete', views.delete_payment, name='delete_payment'),
    path('attendance/<id>/delete', views.delete_attendance,
         name='delete_attendance'),
    path('income/<id>/delete', views.delete_income, name='delete_income'),
    path('genre/<id>/delete', views.delete_genre, name='delete_genre'),
    path('film/<id>/delete', views.delete_film, name='delete_film'),
    path('equipment/<id>/delete', views.delete_equipment, name='delete_equipment'),
    path('film_review/<id>/delete', views.delete_film_review,
         name='delete_film_review'),
    path('create_staff/', views.create_staff, name='create_staff'),
    path('create_rank/', views.create_rank, name='create_rank'),
    path('create_payment/', views.create_payment, name='create_payment'),
    path('create_attendance/', views.create_attendance, name='create_attendance'),
    path('create_income/', views.create_income, name='create_income'),
    path('create_genre/', views.create_genre, name='create_genre'),
    path('create_film/', views.create_film, name='create_film'),
    path('create_equipment/', views.create_equipment, name='create_equipment'),
    path('create_film_review/', views.create_film_review,
         name='create_film_review'),
    path('create_view/', views.create_view, name='create_view'),

]

BD/project/app/models.py
from django.db import models

# Create your models here.


class VideoLibrary(models.Model):
    # shop_id = models.AutoField(primary_key=True, unique=True)
    shop_name = models.CharField(max_length=264)
    adress = models.TextField(max_length=264, default='')

    def __str__(self):
        # return f"{self.shop_name},{self.adress }"
        return f'{self.shop_name}, {self.id}'
        # return self.shop_name + ' ' + self.adress

    class Meta:
        verbose_name_plural = "Video Libraries"


class Staff(models.Model):
    # staff_id = models.AutoField(primary_key=True, unique=True)
    staff_name = models.CharField(max_length=264)
    living_adress = models.TextField(max_length=264)
    gender = models.CharField(max_length=264)
    age = models.IntegerField()
    staff_rating = models.IntegerField()
    shop_name = models.ForeignKey(VideoLibrary, on_delete=models.CASCADE)

    def __str__(self):
        # template = '{0.staff_name}, {0.gender}'
        return f'{self.staff_name}'
        # return template.render(self)

    class Meta:
        verbose_name_plural = "Staff"


class Rank(models.Model):
    # rank_id = models.AutoField(primary_key=True, unique=True)
    staff_name = models.ForeignKey(Staff, on_delete=models.CASCADE)
    rank_name = models.CharField(max_length=264)

    def __str__(self):
        return f'{self.rank_name}, {self.staff_name}'

    class Meta:
        verbose_name_plural = "Ranks"


class Payment(models.Model):
    # payment_id = models.AutoField(primary_key=True)
    rank_name = models.ForeignKey(Rank, on_delete=models.CASCADE)
    payment_amount = models.IntegerField()

    def __str__(self):
        return f'{self.rank_name}, {self.payment_amount}'

    class Meta:
        verbose_name_plural = "Payments"


class Attendance(models.Model):
    # attendance_id = models.AutoField(primary_key=True, unique=True)
    shop_name = models.ForeignKey(VideoLibrary, on_delete=models.CASCADE)
    attendance_amount = models.IntegerField()

    def __str__(self):
        return f'{self.shop_name}, {self.attendance_amount}'

    class Meta:
        verbose_name_plural = "Attendances"


class Income(models.Model):
    # income_id = models.AutoField(primary_key=True, unique=True)
    shop_name = models.ForeignKey(VideoLibrary, on_delete=models.CASCADE)
    income_amount = models.IntegerField()

    def __str__(self):
        return f'{self.shop_name}, {self.income_amount}, {self.id}'

    class Meta:
        verbose_name_plural = "Income"


class Genre(models.Model):
    # genre_id = models.AutoField(primary_key=True, unique=True)
    shop_name = models.ForeignKey(VideoLibrary, on_delete=models.CASCADE)
    genre_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.genre_name

    class Meta:
        verbose_name_plural = "Genres"


class Films(models.Model):
    # film_id = models.AutoField(primary_key=True, unique=True)
    shop_name = models.ForeignKey(VideoLibrary, on_delete=models.CASCADE)
    genre_name = models.ForeignKey(Genre, on_delete=models.CASCADE)
    film_name = models.CharField(max_length=264)
    copies_amount = models.IntegerField()
    film_cost = models.IntegerField()

    def __str__(self):
        return f'{self.film_name}, {self.genre_name}'

    class Meta:
        verbose_name_plural = "Films"


class Equipment(models.Model):
    # equipment_id = models.AutoField(primary_key=True, unique=True)
    shop_name = models.ForeignKey(VideoLibrary, on_delete=models.CASCADE)
    equipment_name = models.CharField(max_length=264)

    def __str__(self):
        return self.equipment_name

    class Meta:
        verbose_name_plural = "Equipment"


class FilmReview(models.Model):
    # film_review_id = models.AutoField(primary_key=True, unique=True)
    film_name = models.ForeignKey(Films, on_delete=models.CASCADE)
    review_amount = models.IntegerField()
    review_score = models.IntegerField()

    def __str__(self):
        return f'{self.film_name}, {self.review_score}'

    class Meta:
        verbose_name_plural = "Film Reviews"

BD/project/templates/app/create_view.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/create_view_master.css' %}" />
  </head>
  <body>
    <form action="/create_shop">
      <input type="submit" id="btn_delete" value="Create Shop" />
    </form>

    <form action="/create_staff">
      <input type="submit" id="btn_delete" value="Create Staff" />
    </form>
    <form action="/create_rank">
      <input type="submit" id="btn_delete" value="Create Rank" />
    </form>
    <form action="/create_attendance">
      <input type="submit" id="btn_delete" value="Create Attendance" />
    </form>
    <form action="/create_income">
      <input type="submit" id="btn_delete" value="Create Income" />
    </form>
    <form action="/create_payment">
      <input type="submit" id="btn_delete" value="Create Payment" />
    </form>
    <form action="/create_film">
      <input type="submit" id="btn_delete" value="Create Film" />
    </form>
    <form action="/create_genre">
      <input type="submit" id="btn_delete" value="Create Genre" />
    </form>
    <form action="/create_equipment">
      <input type="submit" id="btn_delete" value="Create Equipment" />
    </form>
    <form action="/create_film_review">
      <input type="submit" id="btn_delete" value="Create Film Review" />
    </form>
    <form action="/main">
        <input type="submit" class='btn_no' value="Go Back" />
      </form>

  </body>
</html>

BD/project/templates/app/delete_view.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

  </head>
  <body>
    <div class="main">
      <form method="POST">
        {% csrf_token %} Do you really want to delete this item?
        <input type="submit" value="Yes" />
        <a href="/">Cancel</a>
      </form>
    </div>
  </body>
</html>

BD/project/templates/app/detail_view.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'css/detail_view_master.css' %}" />
  </head>
  <body>
    <div class="main">
      {{ shop.shop_name }} <br />
      {{ shop.adress }} <br />
      {{ staff.staff_name }} <br />
      {{ staff.living_adress }} <br />
      {{ staff.gender }} <br />
      {{ staff.age }} <br />
      {{ staff.staff_rating }} <br />
      {{ rank.rank_name }} <br />
      {{ payment.payment_amount }} <br />
      {{ attendance.attendance_amount }} <br />
      {{ income.income_amount }} <br />
      {{ genre.genre_name }} <br />
      {{ film.film_name }} <br />
      {{ film.copies_amount }} <br />
      {{ film.film_cost }} <br />
      {{ equipment.equipment_name }} <br />
      {{ film_review.review_amount }} <br />
      {{ film_review.review_score }} <br />
    </div>
  </body>
</html>

BD/project/templates/app/index.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href='{% static 'css/index_master.css' %}' />
  </head>
  <body>
    <div class="container_color" id="cont_color">
      <h1>Welcome to Video Libraries Database!</h1>
      <h2>Open the Database?</h2>
      <form action="main">
        <input
          type="submit"
          class="btn btn-default"
          value="Open VideoLibraries.DB"
          id='button_index'
        />
      </form>
    </div>
    <img src={% static 'images/index_art.jpg' %} alt="error" id='index_art'>

    <!--[if lt IE 7]>
      <p class="browsehappy">
        You are using an <strong>outdated</strong> browser. Please
        <a href="#">upgrade your browser</a> to improve your experience.
      </p>
    <![endif]-->

    <script src="" async defer></script>
  </body>
</html>

BD/project/templates/app/list_view.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href='{% static 'css/list_view_master.css' %}' />
  </head>
  <body>
    <div class="main">
      <form action="/main"> 
        <input
          type="submit"
          class="btn_no"
          value="Go back"
        />
      </form>
      {% for data in library_dataset %}
      ----------------------------------------
      Shop name: {{ data.shop_name }} <br />
      Adress: {{ data.adress }} <br />
      
      <td>
        <a href="{% url 'update_shop' data.id  %}">
          <button type="button" class="btn">Edit Shop Details</button>
        </a>
        <a href="{% url 'delete_shop' data.id  %}">
          <button type="button" class="btn">Delete Shop</button>
        </a>
      </td>
      
      {% for attendance in data.attendance_set.all %}
      <br>
      Attendance - {{ attendance.attendance_amount }}
      <td>
        <a href="{% url 'update_attendance' attendance.id  %}">
          <button type="button" class="btn">Edit Attendance Details</button>
        </a>
        <a href="{% url 'delete_attendance' attendance.id  %}">
          <button type="button" class="btn">Delete Attendance</button>
        </a>
      </td>
      {% endfor %}
      
      {% for income in data.income_set.all %}
      <br>
      Income - {{ income.income_amount }}
      <td>
        <a href="{% url 'update_income' income.id  %}">
          <button type="button" class="btn">Edit Income Details</button>
        </a>
        <a href="{% url 'delete_income' income.id  %}">
          <button type="button" class="btn">Delete Income</button>
        </a>
      </td>
      {% endfor %}
      <br>
      Equipment:
      <br>
      {% for equipment in data.equipment_set.all %}
      {{ equipment.equipment_name }}
      <td>
        <a href="{% url 'update_equipment' equipment.id  %}">
          <button type="button" class="btn">Edit Equipment Details</button>
        </a>
        <a href="{% url 'delete_equipment' equipment.id  %}">
          <button type="button" class="btn">Delete Equipment</button>
        </a>
      </td>
      {% endfor %}
      <br>
      {% comment %} {% comment %} Genres:
      <br> 
      {% for genre in data.genre_set.all %}
      <ul><li>{{ genre.genre_name }}
        <td>
          <a href="{% url 'update_genre' genre.id  %}">
            <button type="button" class="btn">Edit Genre Details</button>
          </a>
          <a href="{% url 'delete_genre' genre.id  %}">
            <button type="button" class="btn">Delete Genre</button>
          </a>
        </td></ul></li> {% endcomment %} {% endcomment %}

        {% for film in genre.films_set.all %}
        Films in this genre:
        {{ film.film_name }}
          <td>
            <a href="{% url 'update_film' film.id  %}">
              <button type="button" class="btn">Edit Film Details</button>
            </a>
            <a href="{% url 'delete_film' film.id  %}">
              <button type="button" class="btn">Delete Film</button>
            </a>
          </td>

          {% comment %} {% for film_review in film.film_review_set.all %}
          Score of the film: {{ film_review.review_score }}
          {% endfor %} {% endcomment %}
        {% endfor %}

      {% endfor %}
      <br>
      Staff that work in the shop:
      <br />
      <br />
      {% for staff in data.staff_set.all %}
      <ul>
        <li>{{ staff.staff_name }}</li>
        
        <td>
          <a href="{% url 'update_staff' staff.id  %}">
            <button type="button" class="btn">Edit User Details</button>
          </a>
          <a href="{% url 'delete_staff' staff.id  %}">
            <button type="button" class="btn">Delete Staff</button>
          </a>
        </td>
      </ul>

      Rank of different workers:
      {% for rank in staff.rank_set.all %} 
      <ul>
        <li>{{ rank.rank_name }}</li>
        <td>
        <a href="{% url 'update_rank' rank.id  %}">
          <button type="button" class="btn">Edit Rank Details</button>
        </a>
        <a href="{% url 'delete_rank' rank.id  %}">
          <button type="button" class="btn">Delete Rank</button>
        </a>
      </td></ul>


      {% for payment in rank.payment_set.all %} 
      
      Payment details: {{ payment.payment_amount}}
      <td>
        <a href="{% url 'update_payment' payment.id  %}">
          <button type="button" class="btn">Edit Payment Details</button>
        </a>
        <a href="{% url 'delete_payment' payment.id  %}">
          <button type="button" class="btn">Delete Payment</button>
        </a>
      </td></ul>

      
      
      {% endfor %}
      
      <br>
      {% endfor %}
      
      {% endfor %}
      <br>
      
      {% endfor %}
      
      
      {% comment %} {% for data in staff_dataset %} {{ data.age }}
      <br />
      <hr />

      {% endfor %} {% endcomment %}
    </div>
    <script src={% static 'js/show_more.js' %}></script>
  </body>
</html>

BD/project/templates/app/main.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Main Page</title>
    <link rel="stylesheet" href='{% static 'css/main_master.css' %}'>
  </head>
  <body>
    <h1>Here are all Video Libraries:</h1>
    <span id="dots"></span>
    <span id="more">
      {% if shop_name %}
      <ol>
        {% for library in shop_name %}
        <li>Video Library Info</li>
        <ul>
          <li>Name : {{library.shop_name}}</li>
          <li>Adress : {{library.adress}}</li>
          {% comment %} <button id="btn_goto" onclick="">Select</button> {% endcomment %}
        </ul>
        {% endfor %}
      </ol>
      {% else %}
      <p>ERROR</p>
      {% endif %}
    </span>
    <button id="btn_more" onclick="readMore()">Show Info</button>
    <h1>Additional Settings</h1>
    
    <form action="/create_view">
      <input
        type="submit"
        id="btn_delete"
        value="Add info"
      />
    </form>
    <form action="/list_view">
      <input
        type="submit"
        id="btn_delete"
        value="Whole info"
      />
    </form>
    {% comment %} <span><button id="btn_delete" onclick="">Delete Info</button></span> {% endcomment %}
    <p></p>

    {% comment %} {% if shop_name %}
    <select name="shops" id="shop_select" class='box'>
      <option value="" disabled selected id='blank_option' onchange='revealMore()' name='select_option'></option>
      {% for library in shop_name %}
      <option id='library_element'>{{library.shop_name}}</option>
      {% endfor %}
    </select>
    <p></p>
    <input type="text" id='text_area'>
    {% else %}
      <p>ERROR</p>
    {% endif %}
    <p></p>
    <button type="button" onclick='searchMore()'>Confrim</button>
    <table>
      <tr>
        <th>Adress</th>
      </tr>
      <tr>
          <td id='adress'>None</td>
          {% if adress %}
            {% for adress in adress %}
              <td>{{adress.adress}}</td>
            {% endfor %}
          {% endif %}
      </tr>
    </table>   {% endcomment %}
    <script src={% static 'js/show_more.js' %}></script>
  </body>
</html>